-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."plaid_items" add column "plaid_sync_cursor_added_at" timestamptz
--  null;
