table:
  name: plaid_institutions
  schema: public
object_relationships:
  - name: logo_file
    using:
      foreign_key_constraint_on: logo_file_id
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - id
        - name
select_permissions:
  - role: user
    permission:
      columns:
        - id
        - name
      filter: {}
update_permissions:
  - role: user
    permission:
      columns:
        - name
      filter: {}
      check: {}
event_triggers:
  - name: on_insert_plaid_institution
    definition:
      enable_manual: true
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{API_BASE_URL}}/db/events'
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
