-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."user_profiles" add column "timezone" text
--  not null default 'America/New_York';
