table:
  name: airtable_configs
  schema: public
object_relationships:
  - name: destination
    using:
      foreign_key_constraint_on: destination_id
insert_permissions:
  - role: user
    permission:
      check:
        destination:
          user_id:
            _eq: X-Hasura-User-Id
      columns:
        - api_key
        - base_id
        - destination_id
select_permissions:
  - role: user
    permission:
      columns:
        - api_key
        - base_id
        - created_at
        - updated_at
        - destination_id
        - id
      filter:
        destination:
          user_id:
            _eq: X-Hasura-User-Id
update_permissions:
  - role: user
    permission:
      columns:
        - api_key
        - base_id
      filter:
        destination:
          user_id:
            _eq: X-Hasura-User-Id
      check:
        destination:
          user_id:
            _eq: X-Hasura-User-Id
delete_permissions:
  - role: user
    permission:
      backend_only: false
      filter:
        destination:
          user_id:
            _eq: X-Hasura-User-Id
