-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."plaid_items" add column "consent_expires_at" timestamptz
--  null;
