-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."plaid_accounts" add column "is_closed" boolean
--  not null default 'false';
