-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO stripe.intervals_enum (name) VALUES
--   ('month'),
--   ('year'),
--   ('week'),
--   ('day');
