-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."destinations" add column "should_sync_investments" boolean
--  not null default 'false';
