-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO stripe.webhook_events_states (name) VALUES
--   ('processed'),
--   ('failed');
